"""RAG pipeline: retrieval + generation.

This module defines the `RAG` class that orchestrates the two-stage
Retrieval-Augmented Generation process:

1.  **Retrieve** – embed the user's question and query the vector store for
    the most semantically similar document chunks.
2.  **Generate** – build a prompt that includes the retrieved chunks as
    context, send it to a local Ollama LLM, and return the answer along
    with the source filenames that contributed to it.
"""

from typing import List, Dict, Any

import requests

from . import config
from .embedder import Embedder
from .vectorstore import VectorStore


class RAG:
    """Orchestrates retrieval and generation for question answering."""

    def __init__(self) -> None:
        # Initialise the embedding model and vector store once so that
        # subsequent calls to answer() reuse the same resources.
        self._embedder = Embedder(config.EMBED_MODEL)
        self._store = VectorStore(str(config.CHROMA_DIR))

    def answer(self, question: str) -> Dict[str, Any]:
        """Answer a question using retrieved context.

        Args:
            question: The user's natural-language question.

        Returns:
            A dictionary with:
            - ``answer`` (str): The text generated by the LLM.
            - ``sources`` (List[str]): Deduplicated filenames of the chunks
              that were retrieved to build the prompt.
        """
        # ------------------------------------------------------------------
        # STAGE 1: RETRIEVE
        # ------------------------------------------------------------------
        # Convert the question into the same dense embedding space as the
        # document chunks, then ask the vector store for the top-k nearest
        # neighbours.  These chunks are the "evidence" the LLM will use.
        # ------------------------------------------------------------------
        query_embedding = self._embedder.embed([question])[0]
        results = self._store.query(query_embedding, top_k=config.TOP_K)

        # Chroma returns parallel lists; extract the matched chunks and
        # their source metadata.  If nothing is in the index, fall back
        # to empty context.
        chunks: List[str] = results.get("documents", [[]])[0] or []
        metadatas: List[Dict[str, Any]] = results.get("metadatas", [[]])[0] or []

        # Gather unique source filenames to return alongside the answer.
        sources = []
        seen = set()
        for meta in metadatas:
            src = meta.get("source", "unknown")
            if src not in seen:
                seen.add(src)
                sources.append(src)

        # ------------------------------------------------------------------
        # STAGE 2: GENERATE
        # ------------------------------------------------------------------
        # Build a prompt that grounds the LLM strictly in the retrieved
        # chunks.  Explicitly instruct it to answer ONLY from the provided
        # context and to say "I don't know" when the information is absent.
        # This reduces hallucination and keeps answers faithful to the docs.
        # ------------------------------------------------------------------
        context = "\n\n---\n\n".join(chunks)
        if not context:
            # No indexed documents yet – short-circuit without calling the LLM.
            return {
                "answer": "I don't know – no documents have been indexed yet.",
                "sources": [],
            }

        prompt = (
            "You are a helpful assistant. Use ONLY the context below to answer "
            "the question. If the answer is not contained in the context, "
            'reply exactly "I don\'t know". Do not make up information.\n\n'
            f"Context:\n{context}\n\n"
            f"Question: {question}\n\n"
            "Answer:"
        )

        # Call the local Ollama API.
        response = requests.post(
            f"{config.OLLAMA_URL}/api/generate",
            json={
                "model": config.LLM_MODEL,
                "prompt": prompt,
                "stream": False,
            },
            timeout=120,
        )
        response.raise_for_status()
        data = response.json()

        # Ollama returns the generated text under the "response" key.
        answer_text = data.get("response", "").strip()

        return {"answer": answer_text, "sources": sources}
